.LOGON 192.168.235.130/dbc,dbc; 
DATABASE dp_rdm;

CREATE MULTISET TABLE DP_RDM.ShoppingCartItem AS DP_STG2.ShoppingCartItem
WITH DATA;

CREATE MULTISET TABLE DP_RDM.SpecialOffer AS DP_STG2.SpecialOffer
WITH DATA;

CREATE MULTISET TABLE DP_RDM.SpecialOfferProduct AS DP_STG2.SpecialOfferProduct
WITH DATA;

CREATE MULTISET TABLE DP_RDM.Store AS DP_STG2.Store
WITH DATA;

CREATE MULTISET TABLE DP_RDM.SalesOrderHeaderSalesReason AS DP_STG2.SalesOrderHeaderSalesReason
WITH DATA;

CREATE MULTISET TABLE DP_RDM.SalesPerson AS DP_STG2.SalesPerson
WITH DATA;

CREATE MULTISET TABLE DP_RDM.SalesPersonQuotaHistory AS DP_STG2.SalesPersonQuotaHistory
WITH DATA;


CREATE MULTISET TABLE DP_RDM.SalesReason AS DP_STG2.SalesReason
WITH DATA;

CREATE MULTISET TABLE DP_RDM.SalesTaxRate AS DP_STG2.SalesTaxRate
WITH DATA;


CREATE MULTISET TABLE DP_RDM.SalesTerritory AS DP_STG2.SalesTerritory
WITH DATA;

CREATE MULTISET TABLE DP_RDM.SalesTerritoryHistory AS DP_STG2.SalesTerritoryHistory
WITH DATA;

CREATE MULTISET TABLE DP_RDM.Currency AS DP_STG2.Currency
WITH DATA;

CREATE MULTISET TABLE DP_RDM.CurrencyRate AS DP_STG2.CurrencyRate
WITH DATA;

CREATE MULTISET TABLE DP_RDM.Customer AS DP_STG2.Customer
WITH DATA;

CREATE MULTISET TABLE DP_RDM.CreditCard AS DP_STG2.CreditCard
WITH DATA;

CREATE MULTISET TABLE DP_RDM.PersonCreditCard AS DP_STG2.PersonCreditCard
WITH DATA;

CREATE MULTISET TABLE DP_RDM.SalesOrderHeader AS DP_STG2.SalesOrderHeader
WITH DATA
PRIMARY INDEX(SalesOrderID) 
PARTITION BY RANGE_N  (
   OrderDate BETWEEN DATE '2000-01-01' AND '2019-12-31' EACH INTERVAL '1' MONTH);

CREATE MULTISET TABLE DP_RDM.SalesOrderDetail AS DP_STG2.SalesOrderDetail
WITH DATA
PRIMARY INDEX(SalesOrderID) 
PARTITION BY ProductID;

.LOGOFF