.LOGON 192.168.235.130/DBC,DBC
DATABASE DP_RDM;

CREATE MULTISET TABLE DP_RDM.Address AS DP_STG2.Address
WITH DATA;

CREATE MULTISET TABLE DP_RDM.AddressType AS DP_STG2.AddressType
WITH DATA;

CREATE MULTISET TABLE DP_RDM.BusinessEntityAddress AS DP_STG2.BusinessEntityAddress
WITH DATA;

CREATE MULTISET TABLE DP_RDM.Passwords AS DP_STG2.Passwords
WITH DATA;

CREATE MULTISET TABLE DP_RDM.BusinessEntity AS DP_STG2.BusinessEntity
WITH DATA;

CREATE MULTISET TABLE DP_RDM.CountryRegion AS DP_STG2.CountryRegion
WITH DATA;

CREATE MULTISET TABLE DP_RDM.StateProvince AS DP_STG2.StateProvince
WITH DATA;

CREATE MULTISET TABLE DP_RDM.EmailAddress AS DP_STG2.EmailAddress
WITH DATA;

CREATE MULTISET TABLE DP_RDM.Person AS DP_STG2.Person
WITH DATA;

CREATE MULTISET TABLE DP_RDM.PersonPhone AS DP_STG2.PersonPhone
WITH DATA;

CREATE MULTISET TABLE DP_RDM.PhoneNumberType (
PhoneNumberType INTEGER,
Name1 VARCHAR(8)
)
UNIQUE PRIMARY INDEX (PhoneNumberType);
INSERT INTO DP_RDM.PhoneNumberType
SELECT *
FROM DP_STG2.PhoneNumberType;
.LOGOFF
